// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Acumen.Maps.UIMapMenuClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMapMenu
    {
        
        #region Properties
        public UIAcumenWindow UIAcumenWindow
        {
            get
            {
                if ((this.mUIAcumenWindow == null))
                {
                    this.mUIAcumenWindow = new UIAcumenWindow();
                }
                return this.mUIAcumenWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIAcumenWindow mUIAcumenWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAcumenWindow : BrowserWindow
    {
        
        public UIAcumenWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "A Competitive Edge in Customer Management - Acumen";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAcumen UIAcumen
        {
            get
            {
                if ((this.mUIAcumen == null))
                {
                    this.mUIAcumen = new UIAcumen(this);
                }
                return this.mUIAcumen;
            }
        }
        #endregion
        
        #region Fields
        private UIAcumen mUIAcumen;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAcumen : HtmlDocument
    {
        
        public UIAcumen(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "A Competitive Edge in Customer Management - Acumen";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.acumenci.com/";
            this.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
            #endregion
        }
        
        #region Properties
        public UIHome UIHome
        {
            get
            {
                if ((this.mUIHome == null))
                {
                    this.mUIHome = new UIHome(this);
                }
                return this.mUIHome;
            }
        }
        
        public UISolutions UISolutions
        {
            get
            {
                if ((this.mUISolutions == null))
                {
                    this.mUISolutions = new UISolutions(this);
                }
                return this.mUISolutions;
            }
        }
        
        public UIClientProjects UIClientProjects
        {
            get
            {
                if ((this.mUIClientProjects == null))
                {
                    this.mUIClientProjects = new UIClientProjects(this);
                }
                return this.mUIClientProjects;
            }
        }
        
        public UITeam UITeam
        {
            get
            {
                if ((this.mUITeam == null))
                {
                    this.mUITeam = new UITeam(this);
                }
                return this.mUITeam;
            }
        }
        
        public UIInsights UIInsights
        {
            get
            {
                if ((this.mUIInsights == null))
                {
                    this.mUIInsights = new UIInsights(this);
                }
                return this.mUIInsights;
            }
        }
        
        public UICareers UICareers
        {
            get
            {
                if ((this.mUICareers == null))
                {
                    this.mUICareers = new UICareers(this);
                }
                return this.mUICareers;
            }
        }
        
        public UIContactUs UIContactUs
        {
            get
            {
                if ((this.mUIContactUs == null))
                {
                    this.mUIContactUs = new UIContactUs(this);
                }
                return this.mUIContactUs;
            }
        }
        
        public UIApproach UIApproach
        {
            get
            {
                if ((this.mUIApproach == null))
                {
                    this.mUIApproach = new UIApproach(this);
                }
                return this.mUIApproach;
            }
        }
        #endregion
        
        #region Fields
        private UIHome mUIHome;
        
        private UISolutions mUISolutions;
        
        private UIClientProjects mUIClientProjects;
        
        private UITeam mUITeam;
        
        private UIInsights mUIInsights;
        
        private UICareers mUICareers;
        
        private UIContactUs mUIContactUs;
        
        private UIApproach mUIApproach;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHome : HtmlCustom
    {
        
        public UIHome(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "LI";
            this.SearchProperties["Id"] = "menu-item-502";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_i" +
                "tem page-item-482 current_page_item";
            this.FilterProperties["ControlDefinition"] = "class=\"menu-item menu-item-type-post_typ";
            this.FilterProperties["InnerText"] = "Home";
            this.FilterProperties["TagInstance"] = "4";
            this.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIHomeHyperlink
        {
            get
            {
                if ((this.mUIHomeHyperlink == null))
                {
                    this.mUIHomeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Home";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.acumenci.com/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"http://www.acumenci.com/\"";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIHomeHyperlink.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
                    #endregion
                }
                return this.mUIHomeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIHomeHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UISolutions : HtmlCustom
    {
        
        public UISolutions(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "LI";
            this.SearchProperties["Id"] = "menu-item-500";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "menu-item menu-item-type-post_type menu-item-object-page";
            this.FilterProperties["ControlDefinition"] = "class=\"menu-item menu-item-type-post_typ";
            this.FilterProperties["InnerText"] = "Solutions";
            this.FilterProperties["TagInstance"] = "6";
            this.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UISolutionsHyperlink
        {
            get
            {
                if ((this.mUISolutionsHyperlink == null))
                {
                    this.mUISolutionsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISolutionsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUISolutionsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUISolutionsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUISolutionsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Solutions";
                    this.mUISolutionsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/solutions/";
                    this.mUISolutionsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUISolutionsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.acumenci.com/solutions/";
                    this.mUISolutionsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUISolutionsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"http://www.acumenci.com/solutions/";
                    this.mUISolutionsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUISolutionsHyperlink.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
                    #endregion
                }
                return this.mUISolutionsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUISolutionsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIClientProjects : HtmlCustom
    {
        
        public UIClientProjects(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "LI";
            this.SearchProperties["Id"] = "menu-item-499";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children";
            this.FilterProperties["ControlDefinition"] = "class=\"menu-item menu-item-type-post_typ";
            this.FilterProperties["InnerText"] = "Client Projects\r\n\r\nRelease BTL funds\r\n\r\n";
            this.FilterProperties["TagInstance"] = "7";
            this.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIClientProjectsHyperlink
        {
            get
            {
                if ((this.mUIClientProjectsHyperlink == null))
                {
                    this.mUIClientProjectsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIClientProjectsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIClientProjectsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIClientProjectsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIClientProjectsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Client Projects";
                    this.mUIClientProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/client-projects/";
                    this.mUIClientProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIClientProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.acumenci.com/client-projects/";
                    this.mUIClientProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIClientProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"http://www.acumenci.com/client-pro";
                    this.mUIClientProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIClientProjectsHyperlink.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
                    #endregion
                }
                return this.mUIClientProjectsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIClientProjectsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITeam : HtmlCustom
    {
        
        public UITeam(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "LI";
            this.SearchProperties["Id"] = "menu-item-498";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "menu-item menu-item-type-post_type menu-item-object-page";
            this.FilterProperties["ControlDefinition"] = "class=\"menu-item menu-item-type-post_typ";
            this.FilterProperties["InnerText"] = "Team";
            this.FilterProperties["TagInstance"] = "12";
            this.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UITeamHyperlink
        {
            get
            {
                if ((this.mUITeamHyperlink == null))
                {
                    this.mUITeamHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUITeamHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUITeamHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUITeamHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUITeamHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Team";
                    this.mUITeamHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/team/";
                    this.mUITeamHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUITeamHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.acumenci.com/team/";
                    this.mUITeamHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUITeamHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"http://www.acumenci.com/team/\"";
                    this.mUITeamHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUITeamHyperlink.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
                    #endregion
                }
                return this.mUITeamHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUITeamHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIInsights : HtmlCustom
    {
        
        public UIInsights(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "LI";
            this.SearchProperties["Id"] = "menu-item-1301";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "menu-item menu-item-type-post_type menu-item-object-page";
            this.FilterProperties["ControlDefinition"] = "class=\"menu-item menu-item-type-post_typ";
            this.FilterProperties["InnerText"] = "Insights";
            this.FilterProperties["TagInstance"] = "13";
            this.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIInsightsHyperlink
        {
            get
            {
                if ((this.mUIInsightsHyperlink == null))
                {
                    this.mUIInsightsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIInsightsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIInsightsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIInsightsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIInsightsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Insights";
                    this.mUIInsightsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/insights/";
                    this.mUIInsightsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIInsightsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.acumenci.com/insights/";
                    this.mUIInsightsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIInsightsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"http://www.acumenci.com/insights/\"";
                    this.mUIInsightsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIInsightsHyperlink.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
                    #endregion
                }
                return this.mUIInsightsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIInsightsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UICareers : HtmlCustom
    {
        
        public UICareers(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "LI";
            this.SearchProperties["Id"] = "menu-item-1146";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "menu-item menu-item-type-post_type menu-item-object-page";
            this.FilterProperties["ControlDefinition"] = "class=\"menu-item menu-item-type-post_typ";
            this.FilterProperties["InnerText"] = "Careers";
            this.FilterProperties["TagInstance"] = "14";
            this.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UICareersHyperlink
        {
            get
            {
                if ((this.mUICareersHyperlink == null))
                {
                    this.mUICareersHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICareersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUICareersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUICareersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUICareersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Careers";
                    this.mUICareersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/careers/";
                    this.mUICareersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICareersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.acumenci.com/careers/";
                    this.mUICareersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUICareersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"http://www.acumenci.com/careers/\"";
                    this.mUICareersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUICareersHyperlink.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
                    #endregion
                }
                return this.mUICareersHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUICareersHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContactUs : HtmlCustom
    {
        
        public UIContactUs(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "LI";
            this.SearchProperties["Id"] = "menu-item-497";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "menu-item menu-item-type-post_type menu-item-object-page";
            this.FilterProperties["ControlDefinition"] = "class=\"menu-item menu-item-type-post_typ";
            this.FilterProperties["InnerText"] = "Contact Us";
            this.FilterProperties["TagInstance"] = "15";
            this.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIContactUsHyperlink
        {
            get
            {
                if ((this.mUIContactUsHyperlink == null))
                {
                    this.mUIContactUsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIContactUsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIContactUsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIContactUsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIContactUsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Contact Us";
                    this.mUIContactUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/contact-us/";
                    this.mUIContactUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIContactUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.acumenci.com/contact-us/";
                    this.mUIContactUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIContactUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"http://www.acumenci.com/contact-us";
                    this.mUIContactUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIContactUsHyperlink.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
                    #endregion
                }
                return this.mUIContactUsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIContactUsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIApproach : HtmlCustom
    {
        
        public UIApproach(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "LI";
            this.SearchProperties["Id"] = "menu-item-501";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "menu-item menu-item-type-post_type menu-item-object-page";
            this.FilterProperties["ControlDefinition"] = "class=\"menu-item menu-item-type-post_typ";
            this.FilterProperties["InnerText"] = "Approach";
            this.FilterProperties["TagInstance"] = "5";
            this.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIApproachHyperlink
        {
            get
            {
                if ((this.mUIApproachHyperlink == null))
                {
                    this.mUIApproachHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIApproachHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIApproachHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIApproachHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIApproachHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Approach";
                    this.mUIApproachHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/approach/";
                    this.mUIApproachHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIApproachHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.acumenci.com/approach/";
                    this.mUIApproachHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIApproachHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"http://www.acumenci.com/approach/\"";
                    this.mUIApproachHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIApproachHyperlink.WindowTitles.Add("A Competitive Edge in Customer Management - Acumen");
                    #endregion
                }
                return this.mUIApproachHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIApproachHyperlink;
        #endregion
    }
}
