// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Acumen.Maps.UIMapContactUsClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMapContactUs
    {
        
        #region Properties
        public UIContactUsAcumenWindow UIContactUsAcumenWindow
        {
            get
            {
                if ((this.mUIContactUsAcumenWindow == null))
                {
                    this.mUIContactUsAcumenWindow = new UIContactUsAcumenWindow();
                }
                return this.mUIContactUsAcumenWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIContactUsAcumenWindow mUIContactUsAcumenWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContactUsAcumenWindow : BrowserWindow
    {
        
        public UIContactUsAcumenWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Contact Us - Acumenci";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Contact Us - Acumenci");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIContactUsAcumen UIContactUsAcumen
        {
            get
            {
                if ((this.mUIContactUsAcumen == null))
                {
                    this.mUIContactUsAcumen = new UIContactUsAcumen(this);
                }
                return this.mUIContactUsAcumen;
            }
        }
        #endregion
        
        #region Fields
        private UIContactUsAcumen mUIContactUsAcumen;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContactUsAcumen : HtmlDocument
    {
        
        public UIContactUsAcumen(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Contact Us - Acumenci";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/contact-us/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.acumenci.com/contact-us/";
            this.WindowTitles.Add("Contact Us - Acumenci");
            #endregion
        }
        
        #region Properties
        public UIContent UIContent
        {
            get
            {
                if ((this.mUIContent == null))
                {
                    this.mUIContent = new UIContent(this);
                }
                return this.mUIContent;
            }
        }
        
        public HtmlEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUINameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "your-name";
                    this.mUINameEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUINameEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "wpcf7-form-control wpcf7-text wpcf7-validates-as-required";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"your-name\" class=\"wpcf7-form-contr";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "7";
                    this.mUINameEdit.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        
        public HtmlEdit UICompanyEdit
        {
            get
            {
                if ((this.mUICompanyEdit == null))
                {
                    this.mUICompanyEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICompanyEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUICompanyEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "YourCompany";
                    this.mUICompanyEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICompanyEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICompanyEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICompanyEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "wpcf7-form-control wpcf7-text wpcf7-validates-as-required";
                    this.mUICompanyEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"YourCompany\" class=\"wpcf7-form-con";
                    this.mUICompanyEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "8";
                    this.mUICompanyEdit.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUICompanyEdit;
            }
        }
        
        public HtmlEdit UILocationEdit
        {
            get
            {
                if ((this.mUILocationEdit == null))
                {
                    this.mUILocationEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILocationEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUILocationEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "YourLocation";
                    this.mUILocationEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILocationEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILocationEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILocationEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "wpcf7-form-control wpcf7-text wpcf7-validates-as-required";
                    this.mUILocationEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"YourLocation\" class=\"wpcf7-form-co";
                    this.mUILocationEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "9";
                    this.mUILocationEdit.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUILocationEdit;
            }
        }
        
        public HtmlEdit UIPhoneEdit
        {
            get
            {
                if ((this.mUIPhoneEdit == null))
                {
                    this.mUIPhoneEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPhoneEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIPhoneEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Telephone";
                    this.mUIPhoneEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPhoneEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPhoneEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPhoneEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "wpcf7-form-control wpcf7-text";
                    this.mUIPhoneEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Telephone\" class=\"wpcf7-form-contr";
                    this.mUIPhoneEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "10";
                    this.mUIPhoneEdit.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUIPhoneEdit;
            }
        }
        
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "your-email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-valid" +
                        "ates-as-email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"your-email\" class=\"wpcf7-form-cont";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "11";
                    this.mUIEmailEdit.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public HtmlEdit UISubjectEdit
        {
            get
            {
                if ((this.mUISubjectEdit == null))
                {
                    this.mUISubjectEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISubjectEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUISubjectEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "your-subject";
                    this.mUISubjectEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISubjectEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISubjectEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUISubjectEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "wpcf7-form-control wpcf7-text";
                    this.mUISubjectEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"your-subject\" class=\"wpcf7-form-co";
                    this.mUISubjectEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "12";
                    this.mUISubjectEdit.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUISubjectEdit;
            }
        }
        
        public HtmlTextArea UIMessageEdit
        {
            get
            {
                if ((this.mUIMessageEdit == null))
                {
                    this.mUIMessageEdit = new HtmlTextArea(this);
                    #region Search Criteria
                    this.mUIMessageEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIMessageEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "your-message";
                    this.mUIMessageEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIMessageEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIMessageEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "wpcf7-form-control wpcf7-textarea";
                    this.mUIMessageEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"your-message\" class=\"wpcf7-form-co";
                    this.mUIMessageEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIMessageEdit.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUIMessageEdit;
            }
        }
        
        public UIMissing UIMissing
        {
            get
            {
                if ((this.mUIMissing == null))
                {
                    this.mUIMissing = new UIMissing(this);
                }
                return this.mUIMissing;
            }
        }
        
        public UIInvalid UIInvalid
        {
            get
            {
                if ((this.mUIInvalid == null))
                {
                    this.mUIInvalid = new UIInvalid(this);
                }
                return this.mUIInvalid;
            }
        }
        #endregion
        
        #region Fields
        private UIContent mUIContent;
        
        private HtmlEdit mUINameEdit;
        
        private HtmlEdit mUICompanyEdit;
        
        private HtmlEdit mUILocationEdit;
        
        private HtmlEdit mUIPhoneEdit;
        
        private HtmlEdit mUIEmailEdit;
        
        private HtmlEdit mUISubjectEdit;
        
        private HtmlTextArea mUIMessageEdit;
        
        private UIMissing mUIMissing;
        
        private UIInvalid mUIInvalid;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContent : HtmlCustom
    {
        
        public UIContent(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "SECTION";
            this.SearchProperties["Id"] = "content-wrapper";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"content-wrapper\"";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Contact Us - Acumenci");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIAcumenContactAddress
        {
            get
            {
                if ((this.mUIAcumenContactAddress == null))
                {
                    this.mUIAcumenContactAddress = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAcumenContactAddress.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIAcumenContactAddress.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAcumenContactAddress.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Acumen Commercial Insights Ltd\r\n\r\n26 Geo";
                    this.mUIAcumenContactAddress.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAcumenContactAddress.FilterProperties[HtmlDiv.PropertyNames.Class] = "nine column ";
                    this.mUIAcumenContactAddress.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"nine column \"";
                    this.mUIAcumenContactAddress.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "17";
                    this.mUIAcumenContactAddress.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUIAcumenContactAddress;
            }
        }
        
        public HtmlDiv UIAcumentPhoneEmail
        {
            get
            {
                if ((this.mUIAcumentPhoneEmail == null))
                {
                    this.mUIAcumentPhoneEmail = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAcumentPhoneEmail.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIAcumentPhoneEmail.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAcumentPhoneEmail.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Client enquiries\r\n Tel: +44 (0)20 8334 0";
                    this.mUIAcumentPhoneEmail.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAcumentPhoneEmail.FilterProperties[HtmlDiv.PropertyNames.Class] = "nine column ";
                    this.mUIAcumentPhoneEmail.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"nine column \"";
                    this.mUIAcumentPhoneEmail.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "23";
                    this.mUIAcumentPhoneEmail.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUIAcumentPhoneEmail;
            }
        }
        
        public HtmlHyperlink UIClientEmailHyperlink
        {
            get
            {
                if ((this.mUIClientEmailHyperlink == null))
                {
                    this.mUIClientEmailHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIClientEmailHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIClientEmailHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIClientEmailHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIClientEmailHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "info@acumenci.com";
                    this.mUIClientEmailHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIClientEmailHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIClientEmailHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "mailto:info@acumenci.com";
                    this.mUIClientEmailHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIClientEmailHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"mailto:info@acumenci.com\"";
                    this.mUIClientEmailHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIClientEmailHyperlink.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUIClientEmailHyperlink;
            }
        }
        
        public HtmlHyperlink UISupportEmailHyperlink
        {
            get
            {
                if ((this.mUISupportEmailHyperlink == null))
                {
                    this.mUISupportEmailHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISupportEmailHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUISupportEmailHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUISupportEmailHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUISupportEmailHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "support@acumenci.com";
                    this.mUISupportEmailHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUISupportEmailHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUISupportEmailHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "mailto:support@acumenci.com";
                    this.mUISupportEmailHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUISupportEmailHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"mailto:support@acumenci.com\"";
                    this.mUISupportEmailHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUISupportEmailHyperlink.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUISupportEmailHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIAcumenContactAddress;
        
        private HtmlDiv mUIAcumentPhoneEmail;
        
        private HtmlHyperlink mUIClientEmailHyperlink;
        
        private HtmlHyperlink mUISupportEmailHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMissing : HtmlDiv
    {
        
        public UIMissing(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "wpcf7-f682-p495-o1";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Name (required)\r\n \r\n\r\nCompany (required)";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "wpcf7";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"wpcf7\" id=\"wpcf7-f682-p495-o1\" lang=\"en-US\" dir=\"ltr\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "25";
            this.WindowTitles.Add("Contact Us - Acumenci");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UISendButton
        {
            get
            {
                if ((this.mUISendButton == null))
                {
                    this.mUISendButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISendButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUISendButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISendButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Send";
                    this.mUISendButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISendButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISendButton.FilterProperties[HtmlButton.PropertyNames.Class] = "wpcf7-form-control wpcf7-submit";
                    this.mUISendButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"wpcf7-form-control wpcf7-submit\" ";
                    this.mUISendButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "12";
                    this.mUISendButton.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUISendButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUISendButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIInvalid : HtmlDiv
    {
        
        public UIInvalid(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "wpcf7-f682-p495-o1";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Validation errors occurred. Please confi";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "wpcf7";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"wpcf7\" id=\"wpcf7-f682-p495-o1\" lang=\"en-US\" dir=\"ltr\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "25";
            this.WindowTitles.Add("Contact Us - Acumenci");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIInvalidMessageEmail
        {
            get
            {
                if ((this.mUIInvalidMessageEmail == null))
                {
                    this.mUIInvalidMessageEmail = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIInvalidMessageEmail.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIInvalidMessageEmail.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIInvalidMessageEmail.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Email address seems invalid.";
                    this.mUIInvalidMessageEmail.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIInvalidMessageEmail.FilterProperties[HtmlDiv.PropertyNames.Class] = "wpcf7-not-valid-tip";
                    this.mUIInvalidMessageEmail.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"wpcf7-not-valid-tip\" role=\"alert\"";
                    this.mUIInvalidMessageEmail.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "11";
                    this.mUIInvalidMessageEmail.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUIInvalidMessageEmail;
            }
        }
        
        public HtmlSpan UIMissingName
        {
            get
            {
                if ((this.mUIMissingName == null))
                {
                    this.mUIMissingName = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIMissingName.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIMissingName.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIMissingName.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Please fill the required field.";
                    this.mUIMissingName.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIMissingName.FilterProperties[HtmlDiv.PropertyNames.Class] = "wpcf7-not-valid-tip";
                    this.mUIMissingName.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"wpcf7-not-valid-tip\" role=\"alert\"";
                    this.mUIMissingName.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
                    this.mUIMissingName.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUIMissingName;
            }
        }
        
        public HtmlSpan UIMissingCompany
        {
            get
            {
                if ((this.mUIMissingCompany == null))
                {
                    this.mUIMissingCompany = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIMissingCompany.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIMissingCompany.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIMissingCompany.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Please fill the required field.";
                    this.mUIMissingCompany.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIMissingCompany.FilterProperties[HtmlDiv.PropertyNames.Class] = "wpcf7-not-valid-tip";
                    this.mUIMissingCompany.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"wpcf7-not-valid-tip\" role=\"alert\"";
                    this.mUIMissingCompany.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "6";
                    this.mUIMissingCompany.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUIMissingCompany;
            }
        }
        
        public HtmlSpan UIMissingLocation
        {
            get
            {
                if ((this.mUIMissingLocation == null))
                {
                    this.mUIMissingLocation = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIMissingLocation.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIMissingLocation.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIMissingLocation.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Please fill the required field.";
                    this.mUIMissingLocation.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIMissingLocation.FilterProperties[HtmlDiv.PropertyNames.Class] = "wpcf7-not-valid-tip";
                    this.mUIMissingLocation.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"wpcf7-not-valid-tip\" role=\"alert\"";
                    this.mUIMissingLocation.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "8";
                    this.mUIMissingLocation.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUIMissingLocation;
            }
        }
        
        public HtmlSpan UIMissingEmail
        {
            get
            {
                if ((this.mUIMissingEmail == null))
                {
                    this.mUIMissingEmail = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIMissingEmail.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIMissingEmail.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIMissingEmail.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Please fill the required field.";
                    this.mUIMissingEmail.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIMissingEmail.FilterProperties[HtmlDiv.PropertyNames.Class] = "wpcf7-not-valid-tip";
                    this.mUIMissingEmail.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"wpcf7-not-valid-tip\" role=\"alert\"";
                    this.mUIMissingEmail.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "11";
                    this.mUIMissingEmail.WindowTitles.Add("Contact Us - Acumenci");
                    #endregion
                }
                return this.mUIMissingEmail;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIInvalidMessageEmail;
        
        private HtmlSpan mUIMissingName;
        
        private HtmlSpan mUIMissingCompany;
        
        private HtmlSpan mUIMissingLocation;
        
        private HtmlSpan mUIMissingEmail;
        #endregion
    }
}
